# Generated by Django 4.2.16 on 2024-09-26 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0002_project_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="efforts",
        ),
        migrations.AddField(
            model_name="task",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="task_author",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    (0, "CREATED"),
                    (1, "IN PROGRESS"),
                    (2, "PAUSED"),
                    (3, "COMPLETED"),
                ],
                default=0,
                max_length=7,
            ),
        ),
    ]
