# Generated by Django 4.2.16 on 2024-09-26 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_remove_project_efforts_task_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="complete_percentage",
            field=models.FloatField(
                default=0,
                max_length=2,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
