# Generated by Django 4.2.16 on 2024-10-02 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0009_alter_task_creation_date_alter_task_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project",
                to="dashboard.project",
            ),
        ),
    ]
