# Generated by Django 4.2.16 on 2024-10-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0010_alter_task_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "CREATED"),
                    (1, "IN PROGRESS"),
                    (2, "PAUSED"),
                    (3, "COMPLETED"),
                ],
                default=0,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "On Due"), (2, "Overdue"), (3, "Done")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "CREATED"),
                    (1, "IN PROGRESS"),
                    (2, "PAUSED"),
                    (3, "COMPLETED"),
                ],
                default=0,
                null=True,
            ),
        ),
    ]
