# Generated by Django 4.2.16 on 2024-10-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0011_alter_project_status_alter_task_due_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="dead_line",
            field=models.DateTimeField(),
        ),
    ]
