# Generated by Django 4.2.16 on 2024-10-29 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0015_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="responsible",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="company_responsible",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
