# Generated by Django 4.2.16 on 2024-10-29 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0016_company_responsible"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="city",
            new_name="address",
        ),
    ]
