# Generated by Django 4.2.16 on 2024-11-23 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0018_alter_project_responsible_alter_task_responsible"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="prerequisites",
        ),
    ]
